### PR TITLE
New GPLOT branch 'feature/realtime2022'

### PR DESCRIPTION
**Pull request by ghassan-alaka**
This PR forks the _realtime2022_ branch from the **[ghassan-alaka/GPLOT](https://github.com/ghassan-alaka/GPLOT)** repository to the _feature/realtime2022_ branch in the **[hafs-community/GPLOT](https://github.com/hafs-community/GPLOT)** repository to support real-time experiments for HAFS v1.0 and countless other numerical weather prediction models (HWRF, HMON, GFS, ECMWF, etc.). GPLOT is a submodule of the **hafs-community/HAFS** repository, and it drives the **hrdgraphics** Rocoto task in the HAFS workflow.

_feature/realtime2022_ was branched from _support/HAFSv0.3_, which supported HAFS v0.3 experiments. The most significant upgrade is the unification of GPLOT branches for workflow (e.g., Rocoto) jobs and non-workflow (e.g., cron) jobs. Going forward, one unified branch can be used for all experiments, greatly streamlining the development process.

This has been tested on RDHPCS Jet, Hera, & Orion. Note that further upgrades to the _feature/realtime2022_ branch might be necessary based on additional testing.

### CODE REVIEW

**Comment by ghassan-alaka** [comment]
Several key enhancements were developed, implemented, and tested by @lgramer . He will describe these enhancements in some detail below.

**Comment by ghassan-alaka** [comment]
This specific GPLOT branch _realtime2022_ was extensively tested, especially by @AndrewHazelton . He might have a few comments on this.

**Comment by BinLiu-NOAA** [comment]
@ghassan-alaka, I saw this PR add hycom *.a/b fix files into the repo, which should be avoided as much as possible.
The sorc/GPLOT/python/modules/centroid.cpython-39-x86_64-linux-gnu.so file, not sure why this file is needed. In general, we should avoid adding any binary files into Git repositories. Thanks!

**Comment by ghassan-alaka** [comment]
@BinLiu-NOAA - I will defer to @lgramer who required those files for his graphics.

**Comment by AndrewHazelton** [comment]
@BinLiu-NOAA can't speak for the hycom part, but the centroid code is needed for the Polar module. This option seems better than having the user compile it on their own, but let us know if you have another opinion.

**Comment by BinLiu-NOAA** [comment]
@AndrewHazelton I don't know how this sorc/GPLOT/python/modules/centroid.cpython-39-x86_64-linux-gnu.so can work on different platforms (Orion, Jet, Hera). But in general, if it is python module related, then it is better to set and load the correct python version/environment on the supported platforms. The caveat of including a binary file into a Git repository is that it will always be there in the repository history (affecting repository size), even in the future it is deleted by a later commit.

**Comment by ghassan-alaka** [comment]
@BinLiu-NOAA This centroid module for Python is not available anywhere else by default. How do we ensure that future users have this critical module?

**Comment by ghassan-alaka** [comment]
@BinLiu-NOAA I made some changes to remove the *so binary files from the repository. Now, these Python module binary files are created in one of two ways: 1) run a new shell script or 2) allow the GPLOT workflow to automatically detect and, if necessary, build the necessary files. I pushed this commit to my personal repo and will try to cherry pick it for this PR.

**Review by AndrewHazelton — COMMENTED** [review]
I guess this assumes a user has numpy to build the .so file, which is fine because otherwise none of the other code will run.

**Review by lgramer — APPROVED** [review]

**Review by lgramer — APPROVED** [review]
Merge includes significant speed-ups, enhancements, and bug fixes, including new module to produce graphics for ocean model output and new module to produce graphics of interest for air-sea processes. Well tested both within HAFS workflow and stand-alone.

**Pull request merged**
